name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile code
      run: |
        javac -d out src/**/*.java
    - name: Run tests
      run: |
        java -cp out org.junit.runner.JUnitCore test/*.java
